version: '3'

services:
  test_database:
    image: 'bitnami/postgresql'
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=test
    volumes:
      - 'test_postgresql_data:/bitnami/postgresql'
  
  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app
    volumes:
      - 'postgresql_data:/bitnami/postgresql' # for data persistence

  api:
    image: node:lts-bullseye-slim
    depends_on:
      - database
    command: yarn dev:server
    ports:
      - 5000:5000
      - 9229:9229 # debugger port
    working_dir: /src
    volumes:
      - ./:/src

volumes:
  postgresql_data:
    driver: local

  test_postgresql_data:
    driver: local


